### PR TITLE
Card no: #3

### PR DESCRIPTION
**Pull request by sayalis-cuelogic**
Card link: https://trello.com/c/WAINd6Gy

Implemented add new post in blog site and done validations for the same.

### CODE REVIEW

**Comment by sayalis-cuelogic** [comment]
Implemented add post using django form.
All validations for add post is done.

**Comment by sayalis-cuelogic** [comment]
Added requirement and README files.
Changed size of post add form and alignment of is_publish field.

**Comment by aloka-cuelogic** [comment]
Reviewed

**Comment by aloka-cuelogic** [comment]
Tested the functionality
Login And add new blog working as expected.
Code having no issue.

Currently User Object is passed as a separate argument once the remaining task are over
Please try to get user from session objects.
i.e. request.user

@onkartibe currently merging as functionality is working as expected.

**Pull request merged**
